export { default as SplashScreen } from './SplashScreen';
export { default as HomeScreen } from './HomeScreen';
export { default as SchoolSelectionScreen } from './SchoolSelectionScreen';
export { default as ReportFormScreen } from './ReportFormScreen';
export { default as ReportConfirmationScreen } from './ReportConfirmationScreen';
export { default as TrackReportScreen } from './TrackReportScreen';
export { default as DiscussionScreen } from './DiscussionScreen';
export { default as LoginScreen } from './LoginScreen';
export { default as SchoolDashboardScreen } from './SchoolDashboardScreen';
